const chambers = [
  {
    id: 0,
    hospital_name: "Park view",
    address: "test",
    tp_attended: "12",
    tp_registered: "30",
    mp_attended: "275",
    totalp_attended: "1543",
    wp_attended: "544",
    tap_attended: "958",
    chartdata: {
      2024: [
        { month: "January", walkInPatients: 200, appointmentPatients: 15 },
        { month: "February", walkInPatients: 125, appointmentPatients: 18 },
        { month: "March", walkInPatients: 25, appointmentPatients: 18 },
        { month: "April", walkInPatients: 5, appointmentPatients: 18 },
        { month: "May", walkInPatients: 50, appointmentPatients: 180 },
        { month: "June", walkInPatients: 5, appointmentPatients: 80 },
        { month: "July", walkInPatients: 25, appointmentPatients: 15 },
        { month: "August", walkInPatients: 174, appointmentPatients: 111 },
        { month: "September", walkInPatients: 300, appointmentPatients: 124 },
        { month: "October", walkInPatients: 25, appointmentPatients: 234 },
        { month: "November", walkInPatients: 75, appointmentPatients: 179 },
        { month: "December", walkInPatients: 10, appointmentPatients: 90 },
      ],
      2025: [
        { month: "January", walkInPatients: 200, appointmentPatients: 15 },
        { month: "February", walkInPatients: 50, appointmentPatients: 18 },
        { month: "March", walkInPatients: 255, appointmentPatients: 18 },
        { month: "April", walkInPatients: 25, appointmentPatients: 18 },
        { month: "May", walkInPatients: 5, appointmentPatients: 18 },
        { month: "June", walkInPatients: 50, appointmentPatients: 18 },
        { month: "July", walkInPatients: 75, appointmentPatients: 18 },
        { month: "August", walkInPatients: 37, appointmentPatients: 18 },
        { month: "September", walkInPatients: 225, appointmentPatients: 18 },
        { month: "October", walkInPatients: 255, appointmentPatients: 18 },
        { month: "November", walkInPatients: 5, appointmentPatients: 18 },
        { month: "December", walkInPatients: 250, appointmentPatients: 18 },
      ],
    },
  },
  {
    id: 1,
    hospital_name: "metro politonsf sfsfsfsfs sfasf",
    address: "test 2",
    tp_attended: "22",
    tp_registered: "60",
    mp_attended: "75",
    totalp_attended: "543",
    wp_attended: "54",
    tap_attended: "95",
    chartdata: {
      2024: [
        { month: "January", walkInPatients: 2, appointmentPatients: 5 },
        { month: "February", walkInPatients: 5, appointmentPatients: 8 },
        { month: "March", walkInPatients: 25, appointmentPatients: 18 },
        { month: "April", walkInPatients: 25, appointmentPatients: 18 },
        { month: "May", walkInPatients: 25, appointmentPatients: 18 },
        { month: "June", walkInPatients: 25, appointmentPatients: 18 },
        { month: "July", walkInPatients: 25, appointmentPatients: 18 },
        { month: "August", walkInPatients: 25, appointmentPatients: 18 },
        { month: "September", walkInPatients: 25, appointmentPatients: 18 },
        { month: "October", walkInPatients: 25, appointmentPatients: 18 },
        { month: "November", walkInPatients: 25, appointmentPatients: 18 },
        { month: "December", walkInPatients: 25, appointmentPatients: 18 },
      ],
    },
  },
];

export default chambers;
